segmentio/analytics-ios

Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m

All info in ticket here: https://segment.zendesk.com/agent/tickets/22136
@travisjeffery

add support for GA remarketing

---

scripts/integrations.json

Update Taplytics to v2.1.20

---

Analytics/Integrations/Taplytics/SEGTaplyticsIntegration.m

I attempted to follow the same format from your other integrations. Let me know if the mapping makes sense.

updating Taplytics integration to support user attributes and analytics

---

Analytics/Integrations/Mixpanel/SEGMixpanelIntegration.m

See expected behaviour from documentation:
https://segment.com/docs/api/tracking/identify/#special-traits
Untested.

Fix mapping of createdAt -> $created

---

Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m

localytics customer lifetime value

---

Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m

https://segment.zendesk.com/agent/tickets/23663

Catch serialization errors

---

Analytics/Integrations/Taplytics/SEGTaplyticsIntegration.m

Added reset user function

---

Analytics/SEGAnalytics.m
AnalyticsTests/AnalyticsTests.m
AnalyticsTests/settings.json

Todo: 
* tests
* update API endpoint

Tracking Plan

---

Analytics.podspec
Analytics/Helpers/SEGReachability.h
Analytics/Helpers/SEGReachability.m

Needed to make these changes to make Analytics work in a swift project that uses cocoapods.

Swift cocoapods fix

---

Analytics/Analytics.h-r
Analytics/Integrations/Taplytics/SEGTaplyticsIntegration.m
Podfile.lock
scripts/integrations.json

- Added group functionality. This is part of aligning all SDKs together as discussed [here](https://github.com/segmentio/analytics.js-integrations/pull/628#issuecomment-104105311).
- Upgraded Taplytics to the latest version.

Added group functionality to Taplytics.

---

Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m

https://trello.com/c/lW9i23fC/24-localytics-enhancements

Custom Dimensions for Localytics

---

Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m

Use infoDictionary and override with values from localizedInfoDictionary

---

scripts/integrations.json

Bump optimizely

---

Analytics/Integrations/Apptimize/SEGApptimizeIntegration.m

Previously everytime the Apptimize integration would be loaded, we would
fire an event for every experiment viewed by the user.
(It didn't actually work since Apptimize only returned experimements for
the session, which would almost alwyas be zero).
Now we hook into Apptimize to detect when an A/B test is viewed, and
fire the event then.

Improve Apptimize Root integration

---

Podfile.lock
scripts/integrations.json

Update Mixpanel from 2.8.1 to 2.8.2

---

Podfile.lock
scripts/integrations.json

update Taplytics integration

---

Analytics/Integrations/Kahuna/SEGKahunaIntegration.h
Analytics/Integrations/Kahuna/SEGKahunaIntegration.m

Fix Kahuna push notification swizzling

---

Podfile.lock
scripts/integrations.json

Update Taplytics to 2.4.0

---

Podfile.lock
scripts/integrations.json

No major changes according to [SDK changelog](https://developers.google.com/analytics/devguides/collection/ios/changelog)

Upgrade GoogleAnalytics to 3.13.0

---

Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m
iOS Tests/Integrations/Localytics/SEGLocalyticsIntegrationTests.m

Closes https://github.com/segmentio/analytics-ios/issues/413 and https://github.com/segmentio/analytics-ios/issues/377

Send revenue to Localytics and not cents

---

Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m

@f2prateek this obviously will need heavy review, especially since this integration does not yet have tests in place to see what I'm (probably) breaking.
Thought process so far:
- set mapped *traits* as custom dimensions **on the tracker**, since they're inherently user or session scoped. like this example:
- set mapped *properties* of events and screen calls on their **respective hits**, since these are most typically hit-scoped. like this example:
Specifically, I'm not certain I'm correctly passing around / referencing / dereferencing the `GAIDictionaryBuilder*` objects (`hit` and `view`). I was going off this: https://github.com/edx/edx-app-ios/blob/master/Pods/GoogleAnalytics-iOS-SDK/GoogleAnalytics/Library/GAIDictionaryBuilder.h#L57-L69

Google Analytics: Add Support for Custom Dimensions and Metrics

---

Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m

Keep reference to tracker as a property so we can cut down the verbosity
of using it.

Refactor GA integration

---

Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m

use metricString not dimensionString to send custom metrics

---

Analytics/SEGAnalyticsUtils.m

Use invariant locale for ISO8601 date formatter

---

Analytics.xcodeproj/project.pbxproj
Podfile.lock
scripts/integrations.json

updating Amplitude SDK to v3.1.1

---

Analytics.xcodeproj/project.pbxproj
Podfile.lock
scripts/integrations.json

Update Amplitude SDK to v3.2.0

---

Podfile.lock
scripts/integrations.json

Update Taplytics SDK to 2.7.14

---

Pod/Classes/Internal/SEGSegmentIntegration.m

Both test suites passing with this fix in place. Not sure if test coverage actually handles this flow.

Proposed fix to allow the alias() call to succeede.

---

Pod/Classes/Internal/SEGSegmentIntegration.m

configuration options.
Closes #490

Respect shouldUseLocationServices and enableAdvertisingTracking

---

Pod/Classes/SEGAnalytics.m

Tracking events (i.e. for Segment spec) and flush/reset are still
asynchronously delivered to integrations.
Implementation:
We use a `initialized` property to indicate when integrations are ready
to receive events. This flag is set to `TRUE` once the integration is
initialized and we've flushed the message queue.
Once `initialized` is true, any events that have opted for synchronous
delivery, will forwarded instantly to integrations.

Make app lifecycle events synchronous.

---

Pod/Classes/Internal/SEGAnalyticsUtils.h
Pod/Classes/Internal/SEGSegmentIntegration.m

Correctly send context.library.version

---

Pod/Classes/Internal/SEGSegmentIntegration.m

SCNetworkReachabilityGetFlags was always setting flags to 0
removing the protocol specifier caused it to work again

Update SEGSegmentIntegration.m to fix reachability

---

Pod/Classes/SEGAnalytics.m

This is critical for detecting push opens when the application does a cold-start (i.e. from suspended/closed) from a push click and the push-clicked signal (i.e. push payload in the launchOptions) is in the userInfo.

 Pass the userInfo dictionary as an argument to the app state handlers #495

---

.buildscript/bootstrap.sh
Makefile

This script is idempotent and can be run multiple times.

Add bootstrap script.

---

Pod/Classes/SEGAnalytics.h

As discussed here https://github.com/segmentio/analytics-ios/issues/513 the notification string is not public. Changed that. Please review & merge ;)

changed SEGAnalyticsIntegrationDidStart to public

---

Pod/Classes/Internal/SEGSegmentIntegration.m

@tonyxiao 
This PR reverts [this change](https://github.com/segmentio/analytics-ios/commit/3aa84ccdb7e69623981dc57db1ec92283a80a260) from back in December that stored the queue in `NSUserDefaults` instead of writing to disk. I've tested this locally and on my device and confirmed that cached traits and events work as expected.
We'll probably want to do a more in-depth refactor of how we manage the queue but reverting to this method should be a good stopgap measure.

revert NSUserDefaults Queue and Traits

---

Pod/Classes/Internal/SEGAnalyticsUtils.m

Add millisecond precision

---

Pod/Classes/Internal/SEGSegmentIntegration.m

This PR removes transferring the queue and traits to disk since they'd previously been written to both locations. These methods could have duplicated events in users queues. It now only checks for the queue and traits in NSUserDefaults and then removes them if present. @tonyxiao @f2prateek

remove transferQueue and transferTraits methods

---

Pod/Classes/Internal/SEGSegmentIntegration.m

Don't send Segment.io: false

---

Pod/Classes/SEGAnalytics.m

Friendly assert messages

---

Example/Podfile.lock
Pod/Classes/Internal/SEGAnalyticsUtils.h
Pod/Classes/Internal/SEGAnalyticsUtils.m
Pod/Classes/Internal/SEGSegmentIntegration.h
Pod/Classes/Internal/SEGSegmentIntegration.m
Pod/Classes/SEGAnalytics.h
Pod/Classes/SEGAnalytics.m

Add anonymous ID retrieval method

---

Pod/Classes/Internal/SEGSegmentIntegration.m

Previously, some pieces of context were set on the batch (static
context such as library info, device info, etc.).
This had the advantage of reducing the payload size (send it once
instead of 20 times in 20 event batch). But by adding gzip support we
don't really need to do this as much anymore.
So now we store the entire context with every payload, which represents the
context at the time of the event (rather than upload) more accurately.
Closes #124

Record entire context for every event.

---

Analytics/Classes/Internal/SEGSegmentIntegration.m

Same as #560 but against the dev branch.
Closes #558

Initialize flush timer on the main thread.

---

.travis.yml
Analytics.podspec
Analytics/Classes/Internal/SEGAnalyticsRequest.m
Analytics/Classes/Internal/SEGLocation.h
Analytics/Classes/Internal/SEGLocation.m
Analytics/Classes/Internal/SEGSegmentIntegration.m
Analytics/Classes/SEGAnalytics.m
Example/Podfile.lock
Example/Pods/Local Podspecs/Analytics.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Target Support Files/Analytics/Info.plist

Just a rebase + squash of #571

Add tvOS Support

---

Analytics/Classes/Internal/SEGSegmentIntegration.m

Update context object with referrer information

---

.travis.yml
Analytics/Classes/Internal/SEGAnalyticsUtils.h
Analytics/Classes/Internal/SEGAnalyticsUtils.m
Analytics/Classes/Internal/SEGReachability.m
Analytics/Classes/Internal/SEGSegmentIntegration.h
Analytics/Classes/Internal/SEGSegmentIntegration.m
Analytics/Classes/Internal/UIViewController+SEGScreen.m
Analytics/Classes/SEGAnalytics.h
Analytics/Classes/SEGAnalytics.m

These commits were overwritten in the Carthage migration.

Fix rebase

---

Analytics/Classes/SEGAnalytics.m

Fix assert typo

---

.travis.yml
Example/Analytics.xcodeproj/xcshareddata/xcschemes/Analytics-Example.xcscheme
Makefile
README.md
circle.yml
codecov.yml

cc @f2prateek ready for merge afaik

Adding code coverage report & misc. build enhancements

---

Analytics/Classes/Internal/SEGSegmentIntegration.m
Example/Analytics/SEGViewController.m

Closes
https://github.com/segmentio/analytics-ios/pull/617 and
https://github.com/segmentio/analytics-ios/issues/616

Fix incorrect referrer access.

---

Analytics/Classes/SEGAnalytics.m

During releasing 3.5.2, I forgot to update the library version.

Fix version in SEGAnalytics.m

---

Analytics.podspec
Analytics/Classes/Internal/SEGHTTPClient.m
Analytics/Classes/SEGAnalytics.m
CHANGELOG.md
Example/Tests/SEGHTTPClientTests.m

Updates cdn hostname from cdn.segment.com to cdn-settings.segment.com

Hotfix 3.5.3

---

Analytics/Classes/Internal/SEGHTTPClient.m

As requested in comments for previous PR 633.

Added comment explaining workaround.

---

Analytics.podspec
Analytics/Classes/Integrations/SEGIntegrationsManager.m
Analytics/Classes/Internal/SEGHTTPClient.h
Analytics/Classes/SEGAnalytics.m
CHANGELOG.md
Example/Tests/HTTPClientTest.swift

cc @f2prateek and @ladanazita . 
This is the inverse of https://github.com/segmentio/analytics-ios/pull/637, but should be A LOT easier to review due to the smaller set of delta.

Merging master into dev

---

Analytics.xcodeproj/project.pbxproj
Analytics/Analytics.h
Analytics/Classes/Crypto/SEGAES256Crypto.h
Analytics/Classes/Crypto/SEGCrypto.h
Analytics/Classes/Integrations/SEGAliasPayload.h
Analytics/Classes/Integrations/SEGGroupPayload.h
Analytics/Classes/Integrations/SEGIdentifyPayload.h
Analytics/Classes/Integrations/SEGIntegration.h
Analytics/Classes/Integrations/SEGIntegrationFactory.h
Analytics/Classes/Integrations/SEGPayload.h
Analytics/Classes/Integrations/SEGScreenPayload.h
Analytics/Classes/Integrations/SEGTrackPayload.h
Analytics/Classes/Internal/SEGAnalyticsUtils.h
Analytics/Classes/Internal/SEGHTTPClient.h
Analytics/Classes/Internal/SEGHTTPClient.m
Analytics/Classes/Internal/SEGReachability.h
Analytics/Classes/Internal/SEGSegmentIntegration.h
Analytics/Classes/Internal/SEGSegmentIntegrationFactory.h
Analytics/Classes/Internal/SEGStoreKitTracker.h
Analytics/Classes/Internal/SEGUserDefaultsStorage.h
Analytics/Classes/SEGAnalytics.h
Analytics/Classes/SEGAnalyticsConfiguration.h
Analytics/Classes/SEGSerializableValue.h
AnalyticsTests/AnalyticsTests.swift
AnalyticsTests/HTTPClientTest.swift
AnalyticsTests/Utils/TestUtils.swift

And help compiler catch bugs via generics / nullability indicators
cc @segmentio/mobile

Make API a lot easier to use in swift

---

Analytics/Classes/Integrations/SEGIntegrationsManager.m

Release 3.6.0-beta

---

Analytics/Classes/SEGAnalytics.m

Ref: https://segment.atlassian.net/browse/BUGS-644
Previously the build was sent and stored as an integer. This can be incorrect since CFBundleVersion can be a string, e.g. `4.5.2`.
The change will check if there is a value stored under the old key. If
there is, it will copied over as a string to the new key, and the old key will be deleted.
This may send a truncated `previous_build` (i.e. "4" instead of "4.5.2") for
the first "Application Updated" call for customers migrating from an
affected version.
Tested locally. An event with the old SDK shows build as `1`: https://cloudup.com/cJY0mSyiLpj
An event with the new SDK shows build as `1.0.00` and previous_build as
`1` https://cloudup.com/cq5fLFpvBVr.
Note that because of this change, there will be an implicit "Application Updated" event …

Send build as string instead of integer.

---

Analytics.xcodeproj/project.pbxproj
Analytics/Classes/Middlewares/SEGMiddleware.h
Analytics/Classes/Middlewares/SEGMiddleware.m
Analytics/Classes/SEGAnalytics.m
Analytics/Classes/SEGAnalyticsConfiguration.h
AnalyticsTests/MiddlewareTests.swift

This allows the creation of custom middlewares such as the following
https://github.com/segmentio/analytics-test-apps/blob/master/AnalyticsIOSTestApp/AnalyticsIOSTestApp/CustomMiddlewares.swift

Adding SEGBlockMiddleware helper and ability to add custom middleware into the middleware stack

---

Analytics/Classes/SEGAnalytics.m
Examples/CocoapodsExample/Podfile.lock

To prevent race condition where app gets killed and changes do not save
(and thus Application Installed might fire twice)
cc @f2prateek

Synchronize NSUserDefaults after we save values to it

---

README.md

Updates the README
By looking at the README
`pod update` a Podfile with `pod 'Analytics` in it
Nah
None
Nooope
**Questions:**
- Does the docs need an update? yes, included
- Are there any security concerns? nope
- Do we need to update engineering / success? nope

Update cocoapods version to 3.6.0 from rc

---

Analytics.xcodeproj/project.pbxproj
AnalyticsTests/AnalyticsTests.swift
AnalyticsTests/MiddlewareTests.swift
AnalyticsTests/TrackingTests.swift
AnalyticsTests/Utils/TestUtils.swift

Adding tests to cover all tracking API methods

Adding TrackingTests

---

Analytics/Classes/Internal/SEGAnalyticsUtils.m
Examples/CocoapodsExample/CocoapodsExample/AppDelegate.m

Remove NSNull from dictionaries prior to sending to integrations

---

Analytics/Info.plist
Examples/CarthageExample/Cartfile
Examples/CarthageExample/Cartfile.resolved
Examples/CarthageExample/CarthageExample/AppDelegate.swift
Examples/CarthageExample/Makefile
RELEASING.md

Add example for how to distribute dynamic framework built by Carthage

---

Analytics.xcodeproj/project.pbxproj
Analytics/Classes/Integrations/SEGIntegrationsManager.h
Analytics/Classes/Integrations/SEGIntegrationsManager.m
AnalyticsTests/AnalyticsTests-Bridging-Header.h
AnalyticsTests/IntegrationsManagerTest.swift

This required exposing some internal methods to simplify testing.
I made those method class methods as they don't rely on any class properties.

Add Integration Manager tests.

---

AnalyticsTests/AnalyticsTests.swift
Examples/CocoapodsExample/Podfile.lock

The continues user activity test is pretty flaky, disable it for now.

Disable "continues user activity test"

---

Analytics.xcodeproj/xcshareddata/xcschemes/AnalyticsTests.xcscheme
AnalyticsTests/EndToEndTests.swift
Makefile
circle.yml

Pass E2E credentials using environment variables

---

AnalyticsTests/AnalyticsTests.swift
AnalyticsTests/EndToEndTests.swift

Ref: LIB-543
- Fix `maxQueueSize` flaky test
- Increase E2E webhook limit

Fix flaky tests

---

.github/stale.yml

This PR adds a config for [stale](https://probot.github.io/apps/stale/) to clean up our old issues and PRs.

add stale configuration

---

Analytics.podspec
Analytics/Classes/SEGAnalytics.m
CHANGELOG.md
Examples/CarthageExample/Cartfile
README.md

- Check versions in info.plist, cart file and podspec.
N/A
Promoting 3.7.0-beta.4 to release.
LIB-1212
N/A
**Questions:**
NO
NO
NO

LIB-1212: Promoting 3.7.0-beta.4 to release.

---

Analytics.podspec
Analytics/Classes/SEGAnalytics.m
Analytics/Info.plist
CHANGELOG.md
Examples/CarthageExample/Cartfile

* Preparing 3.8.0-beta.0 release.

Preparing 3.8.0-beta.0 release. (#837)

---

Analytics/Classes/Integrations/SEGIntegrationsManager.m

Fixes issue where cached versions of analytics-ios don't load 
yes(?)
n/a
n/a
n/a
**Questions:**
no
no
no

Add previouslyCachedSettings count

---

Analytics.xcodeproj/project.pbxproj
AnalyticsTests/EndToEndTests.swift
Podfile
Podfile.lock

Removes dependencies of Alamofire and Alamofire-Synchronous. This also removes hitting the wire for EndToEnd tests.
By verifying the test hitting the wire is completely necessary or not.
By executing tests in EndToEndTests.swift.
**Questions:**
- Does the docs need an update? No
- Are there any security concerns? No
- Do we need to update engineering / success? No

Updated tests to remove Alamofire

---

Analytics/Classes/Integrations/SEGIntegrationsManager.m
Analytics/Classes/Internal/SEGSegmentIntegration.m
Analytics/Classes/Internal/SEGUtils.h
Analytics/Classes/Internal/UIViewController+SEGScreen.h
Analytics/Classes/Internal/UIViewController+SEGScreen.m
Analytics/Classes/SEGAnalytics.m
Analytics/Classes/SEGAnalyticsConfiguration.m

Fixes a crash with UISceneDelegate applications that expect a UIWindow property on the delegate.
Verify it works in both UIApplicationDelegate and UISceneDelegate projects.
Verify it works in both UIApplicationDelegate and UISceneDelegate projects. Also make sure the analytics are still piping in correctly.
The crash was found with an Xcode 11.5 new Swift / storyboard project.
LIBMOBILE-83
**Questions:**

LIB-83: Fixed crash on UISceneDelegate applications

---

Analytics/Classes/SEGAnalytics.m

Repairs an issue where passed in traits were not overriding existing trait values.
Check that the traits are updated.
Pass in new traits via identify
https://segment.atlassian.net/browse/LIBMOBILE-109
**Questions:**
No
No
No, besides me being awesome

LIBMOBILE-109: Updated an issue with new traits not overriding old traits

---

Analytics.xcodeproj/project.pbxproj
Analytics/Classes/Analytics.h

Makes SEGLog public **for reals this time**
Add the library and test SEGLog is available.
**Questions:**

Fixed SEGLog permissions

---

Examples/CarthageExample/Makefile
README.md

Adds badges and updates Carthage Makefile
👀 
Execute `make build` on the carthage example
**Questions:**

Added Carthage and SwiftPM badge

---

Analytics/Classes/SEGAnalytics.h
Analytics/Classes/SEGAnalytics.m
Analytics/Classes/SEGSegmentIntegration.m
Analytics/Internal/SEGIntegrationsManager.m
AnalyticsTests/AnalyticsTests.swift
AnalyticsTests/EndToEndTests.swift

Deprecates configuration
**Questions:**

Deprecated configuration access and updated associated tests

---

Analytics/Classes/SEGAnalytics.m
Analytics/Classes/SEGAnalyticsConfiguration.h
Analytics/Classes/SEGMiddleware.h
Analytics/Internal/SEGIntegrationsManager.m

- Added infrastructure for edge functions.

Added stubs for edge functions.

---

Examples/SegmentMac/SegmentMac.xcodeproj/project.pbxproj
Examples/SegmentMac/SegmentMac.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Examples/SegmentMac/SegmentMac/ViewController.swift

Repairs the Mac example project after Segment rename

Repaired mac example project

---

Examples/FullExampleFlow/Analytics Example.xcodeproj/project.pbxproj
Examples/FullExampleFlow/Analytics Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Examples/FullExampleFlowCatalyst/Analytics Example.xcodeproj/project.pbxproj
Examples/FullExampleFlowCatalyst/Analytics Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Cleans up example apps using an old branch for mac conversion

Fixed example projects using old branch for swift

---

Segment/Classes/SEGSegmentIntegration.m

- Output a log message when events are trimmed from the queue.
- Replicated behavior of Android library.

Output a log message when events are trimmed from the queue

---

Segment/Classes/SEGAnalytics.m
SegmentTests/TrackingTests.swift

Fix issue where userId was not being set within traits like it should be.

---

Segment/Classes/SEGPayload.m
SegmentTests/MiddlewareTests.swift

- Fixes issue where context modified in/for one event is overwritten by a follow-on event.

Fixed issue where context modification is affected between events.
