- Analytics/Integrations/Flurry/SEGFlurryIntegration.m
See 2014 WWDC Session 417. If not casted, the compiler will complains with `Too many arguments to function call, expected 0, have 3`.
> Properly cast objc_msgSend calls

- Analytics/Integrations/Flurry/SEGFlurryIntegration.m
@f2prateek made the same fix to flurry to highlight some ways that https://github.com/segmentio/analytics-ios/pull/250 could have implemented a bit better.
for one we didn't need a separate method to set the default value, since if there is no object for say latitude then that value will be nil, and when any message is sent to nil it's also nil aka 0. kind of an objc behavior thing that can useful to know. 
but let's say the default was something other than 0, another way to do a default like that is `[location objectForKey:@"longitude"] ?: 4;`. where 4 would be the default.
we didn't need to add to this method: 
https://github.com/segmentio/analytics-ios/pull/250#discussion-diff-24203107 but if we did you would have wanted to write it as:
``` objective-c
- …
```
> Add location to flurry

- Podfile.lock
- scripts/integrations.json
* Add opt out method to disable logging for a user
* Fix CLLocationManager authorization constants warning
* Add method for adding new user properties without replacing. Make it default
* Fix base64 string deprecation warning
> Update Amplitude integration to 2.3.0

- Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m
Hi,
I was having trouble using segment as app tracker and GA as [global tracker](https://segment.com/docs/integrations/google-analytics/#multiple-trackers) (multiple GA tracker), because when I set my GA tracker it is set as default and segment wasn't able to track anymore as it uses defaultTracker. 
So I changed this line so the segment tracker will always be the [default](https://developers.google.com/analytics/devguides/collection/ios/v3/advanced#default-tracker), so Segment keeps working and I can yet access my tracker by its ID.
I just changed that file without changing anything else because I don't know your standard for releasing a new version.
Hope it helps, 
Lucas Martins - [ckl.io](ckl.io)
ps. It is a different solution for Pull #272
> Sets the segment tracker always as default

- Analytics/Helpers/SEGBluetooth.m
Reading the address of CBCentralManagerOptionShowPowerAlertKey inline fails
on iOS 6, use a temporary variable to compare.
> Fix for iOS 6 compatibility

- Analytics.xcodeproj/project.pbxproj
- Analytics/Integrations/Apptimize/SEGApptimizeIntegration.h
- Analytics/Integrations/Apptimize/SEGApptimizeIntegration.m
- Analytics/Integrations/SEGAnalyticsIntegrations.h
- Podfile.lock
- scripts/integrations.json
- SEGApptimizeIntegration.
- Copy the Apptimize headers, statically link the framework binary.
This required some Cocoapods calisthenics on our end (we used to ship a versioned directory, but that was a bit incongruous with the other provided SDKs.) and a couple Segment-specific APIs.
> Add Apptimize Integration.

- Analytics/Helpers/SEGBluetooth.m
Simply checking the symbol address was not sufficient on iOS6.
> Explicitly check if selector exists

- Analytics.xcodeproj/project.pbxproj
- Analytics/Integrations/Kahuna/SEGKahunaIntegration.m
Before this change, we were registering the Kahuna observer before enabling it.
> Move push registration to start method

- Analytics/Integrations/Taplytics/SEGTaplyticsIntegration.m
Hey,
Sorry for the extra PR – I didn't think this option would have been needed, but I was horribly wrong!
It's a quick addition:
- `pushSandbox` – either `@0` or `@1` (a number). If it's `@0`, the push token for the device is assumed to be a production token and if `@1`, it's assumed to be a development token.
Cheers!
> Added pushSandbox option to Taplytics.

- Analytics.xcodeproj/project.pbxproj
- Analytics/Integrations/Kahuna/SEGKahunaIntegration.h
- Analytics/Integrations/Kahuna/SEGKahunaIntegration.m
- Analytics/Integrations/SEGKahunaDefines.h
- Podfile.lock
- iOS Tests/Integrations/Kahuna/SEGKahunaIntegrationTests.m
- scripts/integrations.json
Squashed commit of the following:
commit fae7de26601890eb56948bf23a4132f0c64eba22
Author: sharekris <ksubramanian73@gmail.com>
Date:   Wed Jul 29 13:48:49 2015 -0700
Podfile.lock changed to use 2.0.3 after running make build.
commit 0d777e823a139e0c75ad62fc50855994e440f4d2
Merge: f2e88e8 12165d5
Author: SimpliRay <rayleeriver@gmail.com>
Date:   Wed Jul 29 10:27:25 2015 -0700
Merge pull request #1 from sharekris/updating_code_for_2.0.2
Updating code for 2.0.3
commit 12165d52362b697cc89111b86a9c22c713ab4524
Author: sharekris <ksubramanian73@gmail.com>
Date:   Tue Jul 28 17:06:28 2015 -0700
Removed tab.
commit f99b41841f006aea4a22bce3c22215a33cf02ce0
Author: sharekris <ksubramanian73@gmail.com>
Date:   Tue Jul 28 16:39:56 2015 -0700
Changed to version 2.0.3 as that is the latest.
commit …
> Update Kahuna integration and SDK

- Analytics/Integrations/Amplitude/SEGAmplitudeIntegration.m
- Podfile.lock
- scripts/integrations.json
Updating Amplitude SDK to v3.0.0
* No longer log start/end sessions by default; however, users can re-enable them by setting trackSessionEvents to true. This is exposed in Segment via trackSessionEvents settings option.
(Also updated Cocoapods to 0.38?)
> Updating Amplitude SDK v3.0.0

- Analytics/Integrations/Mixpanel/SEGMixpanelIntegration.m
- iOS Tests/Integrations/Mixpanel/SEGMixpanelIntegrationTests.m
cc @wcjohnson11 @sperand-io 
Ref: https://segment.phacility.com/T265
> Support not setting traits on Mixpanel

- Podfile.lock
- scripts/integrations.json
Just a couple of bug fixes: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.0.1
> Updating Amplitude SDK to v3.0.1

- Analytics.xcodeproj/project.pbxproj
- Analytics/Integrations/Flurry/SEGFlurryIntegration.m
- Podfile.lock
- scripts/integrations.json
* Update the SDK to version 7.1.0 (newer versions don't work due to
Xcode 7) incompatibility.
* Remove registerForRemoteNotificationsWithDeviceToken call, since
`setPushToken` doesn't exist anymore.
> Update Flurry integration

- Pod/Classes/Integrations/SEGIdentifyPayload.h
- Pod/Classes/Integrations/SEGIdentifyPayload.m
- Pod/Classes/Internal/SEGSegmentIntegration.m
- Pod/Classes/SEGAnalytics.h
- Pod/Classes/SEGAnalytics.m
This is a first stab at making the Anonymous ID customisable, as asked about in #482. Some more background can be found in [this PR](https://github.com/artsy/eigen/pull/958) on our app.
This is very much a work in progress, I did the bare minimum to get _what we needed_ to work, so now I’m looking for feedback on:
* Is adding this feature conceptually ok?
* Would you prefer I refactor the `-getAnonymousId:` code into e.g. the getter of the `anonymousId` property, or what is the style you’d prefer?
* General code-style
> [Identify] Make Anonymous ID customisable.

- Pod/Classes/Internal/SEGSegmentIntegration.m
When looking for the `userId` and `anonymousId`, look first in
`NSUserDefaults`, then in the stored file. The stored file is persistent
in most cases, but on tvOS, the file system should be treated as
temporary. That means we lose the identity of the user is lost as soon
as the file system is cleared on the Apple TV.
This solution does not replace these file, but simply augments them,
using `NSUserDefaults` as a cache in front of the files. The only
rationale I can think of for using files is that sometimes apps blow
away their defaults.
There is probably another approach here which finds a happy medium, but
`NSUserDefaults` is all we've really got (unless you want to play with
the keychain, and I sure don't) on tvOS.
> Store `userId` and `anonymousId` in NSUserDefaults

- Pod/Classes/Internal/SEGSegmentIntegration.m
Queue and Traits properties should return a mutable object. If they are retrieved from NSUserDefaults they are immutable by default, therefore mutableCopy is needed.
I had to downgrade segment pod to the previous version because of this. It was randomly crashing at launch with AppBoy integration.
> Fix Crash: Mutable queue and traits

- Pod/Classes/Internal/SEGLocation.h
- Pod/Classes/Internal/SEGLocation.m
- Pod/Classes/Internal/SEGSegmentIntegration.m
This PR should address several issues found on version 3.0.4:
- When SEGLocation is initialized from a background thread, it never receives location updates, for this reason I am initializing the locationManager in the main thread.
- SEGSegmentIntegration was initializing SEGLocation every time liveContext method was called (which happens pretty frequently) and shouldUseLocationServices = true. By initializing it all the time we were deallocating the previous instance and allocating a new one and starting the location manager again. This was causing a crash when reverseGeocodeLocation completion handler was called and the syncQueue had already being deallocated. To fix this crash I updated the code to initialize SEGLocation only once.
- SEGLocation->didUpdateLocations was handling …
> Fix location updates issues

- Pod/Classes/SEGAnalytics.h
- Pod/Classes/SEGAnalytics.m
The initializer `-initWithConfiguration:` is missing in the public header file and thus unusable.
It is referred to by the deprecation message of `-initWithWriteKey:` and must be used when creating a non-singleton instance of `SEGAnalytics`.
This pull request adds it to the public header file.
Also this pull request fixes wrong return types specified for the initializers. 
They now return `instancetype` instead of `id`.
> Added missing initializer in SEGAnalytics.h & fixed return types

- Pod/Classes/SEGAnalytics.m
When an `SEGAnalytics` instance gets destroyed the app will crash on certain notifications sent by `NSNotificationCenter` because `SEGAnalytics` never removes itself as an observer.
This pull request properly removes the observers.
> Fixed crashes due to NSNotificationCenter observers not being removed

- Pod/Classes/Internal/SEGSegmentIntegration.m
The segment integration is currently using the old-school selector of  registerForRemoteNotificationsWithDeviceToken:options to handle recieving a notification token. Therefore when [SEGAnalytics registeredForRemoteNotificationsWithDeviceToken:] is called, the integration does not receive the forwarded call.
This PR updates the selector to registeredForRemoteNotificationsWithDeviceToken: so that it once again receives the forwarded calls.
> Fix notification token setting in the segment integration

- Pod/Classes/Internal/SEGSegmentIntegration.m
Created a static instance of CTTelephonyNetworkInfo to avoid a crash caused by a bug in iOS see:
http://stackoverflow.com/questions/14238586/coretelephony-crash
> Added static CTTelephonyNetworkInfo as fix for iOS Bug

- Pod/Classes/SEGAnalytics.m
The Bundle IDs are not very clear, `CFBundleVersion` is the build number (as reflected in Xcode under Project -> General -> Identity -> Build), and the `CFBundleShortVersionString` is the marketing version number (Xcode -> Project -> General -> Identity -> Version)
> Fix Build and Version numbers being reversed

- Pod/Classes/Internal/UIViewController+SEGScreen.m
The automatic screen event code did not handle the case where the root view controller was a UINavigationController.
The code would often just report the top level Nav as it would not always have a presented VC.
This proposed change checks for a top level nav controller, and steps into either it's presented controller or it's last in the list of view controllers as appropriate.
Closes #542 and #543 
cc @voidref
> Handle root being a navigation controller

- Pod/Classes/Internal/SEGReachability.m
This fixes a warning produced by the static analyzer.
Closes #517 and #514 
Just a rebase + against `dev`.
> Fixed analyzer warnings

- Analytics/Classes/Internal/UIViewController+SEGScreen.m
There are scenarios that an alert view controller for instance could be displayed without specifying a title. In that instance the screenTitle.length > 0 assertion would fail.
This fix simply checks that name.length == 0 and if it is then try and generate a useful name.
> Fix for when a title may come back as empty string

- Analytics/Classes/Internal/UIViewController+SEGScreen.h
We were integrating this library using GYP instead of CocoaPods and there was a compilation issue because `UIViewController` is defined in `UIKit` rather than `Foundation`.
> Replace Foundation import with UIKit import

- Analytics/Classes/Internal/SEGSegmentIntegration.m
> Exclude files from backup

- Analytics/Classes/SEGAnalytics.m
Previously events that were marked as disabled in the tracking plan
would still be sent to Segment (and other integrations, both client side
and server side).
The bug was that we were accidentally checking the class name of the
SEGTrackPayload instead of the `event` in the payload.
> correctly skip forwarding disabled events in the tracking plan

- Analytics/Classes/Internal/SEGBluetooth.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalytics.h
- Analytics/Classes/SEGAnalytics.m
- Example/Podfile.lock
- Example/Pods/Local Podspecs/Analytics.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/Analytics/Info.plist
- Example/Tests/Tests.m
Also disables bluetooth collection by default.
> Add option to enable/disable bluetooth collection.

- Analytics/Classes/SEGAnalytics.m
Since 3.5.0 (https://github.com/segmentio/analytics-ios/pull/592/files), a regression was introduced as part of the crypto changes
that would cause a new anonymous ID to be generated for every launch of
the app.
This change fixes that regression.
> Initialize storage before generating anonymous ID.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Example/Tests/AnalyticsTests.swift
- Example/Tests/Analytics_Tests-Bridging-Header.h
This helps ensure bug like https://github.com/segmentio/analytics-ios/pull/615 not happen again
cc @sperand-io  @f2prateek
> Adding a test to test overall persistence of userId and anonymousId. Change setCachedSettings: to not statically dispatch_once

- Analytics/Classes/Internal/SEGSegmentIntegration.m
This fixes what I consider to be a critical bug, reproducible in the Example app.
`SEGSegmentIntegration` currently does not call `UIApplication#endBackgroundTask` until the expiration handler from `beginBackgroundTask` is called, which means the app will remaining running open in the background until the expiration handler is called. `SEGSegmentIntegration` should behave as a good citizen and end the background task as soon as it no longer needs.
To reproduce:
1. Run the Example app in the debugger
2. Press Command-Shift-H to background the app without killing its process.
3. Pause the debugger and type in `po [(UIApplication*)[UIApplication sharedApplication] backgroundTimeRemaining]`
4. Note the result is a large number over 100, indicating the app will remain active for several …
> End background tasks as soon as flushing is complete.

- Analytics/Classes/Internal/SEGHTTPClient.h
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalytics.m
Likely should help fix issue. 
https://segment.atlassian.net/browse/EPD-142
https://segment.atlassian.net/browse/EPD-198
In a separate (not hot fix PR) we should make it easier to have correct threading logic
by letting `SEGHTTPClient` take in a dispatch queue upon initialization
cc @f2prateek @ladanazita
> Re-dispatch callbacks from SEGHTTPClient onto correct queues before executing logic

- Analytics.podspec
- Analytics/Classes/SEGAnalytics.m
cc @f2prateek @ladanazita 
To repro the original buggy behavior
1) Put device in airplane mode and open app
2) Send an event `Application Launched 1`
3) Force kill the app via task switcher
4) Disable airplane mode and regain internet access
5) Launch the app again, send another event `Application Launched 2`
6) Observe that `Application Launched 2` will hit tracking API, while `Application Launched 1` will be missing. 
Basically what happens is that during step 2, if the settings request were to fail, no integrations would be initialized (segment included). This hotfix falls back to segment integration in those cases and we'll have a more comprehensive set of fixes to address this from a design level in development branch.
> Fall back to using Segment integration when we cannot get settings

- Analytics/Classes/Internal/SEGSegmentIntegration.m
This bug would cause serialization issues for the entire queue
@f2prateek @ladanazita
> Fix bad serialization issue with continueUserActivity

- Analytics.xcodeproj/project.pbxproj
issue: #625
This adds possibility to build the framework for apple tv using `carthage update --platform tvOS analytics-ios`
> Add tvOS for deployment target

- Analytics/Classes/Internal/SEGSegmentIntegration.m
Previously liveContext would populate `network.cellular` and
`network.wifi`, whilc staticContext would populate `network.carrier`.
In merging the two, the `network` dictionary in liveContext would
override the one in staticContext, causing `network.carrier` to be
ignored in the merged dictionary.
For now, we're populating the `network.carrier` as part of liveContext
to avoid this conflict.
Another potential fix would be to do a deep merge instead of shallow merge so
that `network.carrier` is preserved. However this would also apply to
custom context dictionaries sent by customers, and might not be the
behaviour they want (e.g. if they sent `context.network` as `{}`, the
deep merge would preserve the fields we collect, while a shallow merge
would ignore it).
> Ensure network.carrier is populated.

- codecov.yml
For certain changes we don't always need the individual patch to meet requirement as long as the overall codebase meets coverage requirements.
> Relax patch coverage requirements

- Analytics/Classes/Internal/SEGStoreKitTracker.m
-- resubmission of pull request: https://github.com/segmentio/analytics-ios/pull/667
It isn't clear to me how to rebase within the context of a pull request so I created a new pull request that follows your contribution guidelines (opened against the dev branch).
I tweaked the change, I opted to modify the trackTransaction:forProduct: method with a "guard" statement because at this point in the code it is clear why we should not allow a nil value through.
----
According to Apple’s documentation (https://developer.apple.com/reference/storekit/skpaymenttransaction) the transactionIdentifier attribute can be nil.
Trying to create a dictionary with a nil value leads to a crash, and we’ve seen this type of crash in production (http://crashes.to/s/8c3d076840e). The nil value would be used with …
> fix: transaction.transactionIdentifier is nullable

- Analytics/Classes/Internal/SEGSegmentIntegration.m
Any reason you are not passing the userInfo that is received to the notification? But instead passing self which properties are mostly private and therefor not accessible.
> Pass through userInfo

- Analytics/Classes/Integrations/SEGIdentifyPayload.h
- Analytics/Classes/SEGAnalytics.h
- Added ‘nullable’ and `_Nullable’ to SEGPayload userId property and
SEGAnalytics identify calls
- Fixes #673
- Ran `make build test` and received ** TEST SUCCEEDED ** in the console.
> Bug Fix #673

- Analytics/Classes/SEGAnalytics.h
- Analytics/Classes/SEGAnalytics.m
- AnalyticsTests/AnalyticsTests.swift
- Examples/CocoapodsExample/CocoapodsExample/AppDelegate.m
- Examples/CocoapodsExample/CocoapodsExample/Assets.xcassets/AppIcon.appiconset/Contents.json
- Examples/CocoapodsExample/CocoapodsExample/Info.plist
- circle.yml
`Application Opened` is now sent when application moves from background to forground. 
`Application Opened` now includes properties listed in our mobile spec (`from_background`, `referring_application`,`url`) when application available.  For example, when launching app from a URL. 
https://segment.atlassian.net/browse/EPD-1153
**Questions:**
Application Backgrounded: https://github.com/segmentio/site-docs/pull/2158/
Application Opened was not updated in Mobile Spec as it is not consistent with Android functionality
cc @teresanesteby
> Fix application opened

- Analytics/Classes/Internal/SEGHTTPClient.m
Add` [session finishTasksAndInvalidate]` to SEGHTTPClient.m to prevent memory leak
You should release the `NSURLSession` object after using it. Details:
Segment SDK is using `[NSURLSession sessionWithConfiguration:config]` to create NSURLSession object for each task rather than a singleton object.
In Apple's [document](https://developer.apple.com/reference/foundation/urlsession), it says: 
> **Important**
> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.
There is also an StackOverflow question discussed about this: [http://stackoverflow.com/a/35757989/2627067](http://stackoverflow.c …
> Add [session finishTasksAndInvalidate] to SEGHTTPClient.m to prevent memory leak

- Analytics/Classes/SEGAnalytics.m
Looks like we missed this in the merge to `3.6.0` and introduced a regression, causing problem with `Application Updated` logic.
> Using string instead of pointer comparision for Application Updated logic

- Analytics/Classes/Internal/SEGSegmentIntegration.m
Hotfix for https://github.com/segmentio/analytics-ios/issues/683
We can sometimes deadlock on `@synchronized(self)` block inside `SEGIntegrationsManager` because both the main queue and `io.segment.analytics.segmentio` queue are trying to acquire a single synchronized lock while the main thread waits for `io.segment.analytics.segmentio` queue via `dispatchBackgroundAndWait` during `endBackgroundTask`. This PR uses a separate queue for `endBackgroundTask` to avoid that issue. This works because the only thing we are trying to make sure is access to `self.backgroundTaskId` is thread-safe. There are no other dependencies on other operations sent to  `io.segment.analytics.segmentio` queue
cc @f2prateek
> Use a separate queue for endBackgroundTask to fix deadlock

- Analytics/Classes/Internal/SEGSegmentIntegration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/Utils/TestUtils.swift
Removes calls to cancel ongoing requests. See #670.
In `SEGSegmentIntegration.m` file where the calls where removed.
Set `flushAt` to some high value, maybe 30. Generate tracking events and then call `reset`. All generated tracking events should be send.
We were calling `reset` after user logged out in our application, but we quickly noticed that calling `reset` also cancels any ongoing request. Since we had `flushAt` set to 5 some of the request generated by the user just before log out action were not send to Segment integration.
#670 
> Remove canceling ongoing requests in reset method.

- Analytics.xcodeproj/project.pbxproj
- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/Internal/UIViewController+SEGScreen.m
- Analytics/Classes/SEGAnalytics.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/Utils/TestUtils.swift
Extract usage of UIApplication into protocol and optional property on config, so the sdk can be used with iOS extensions.
SEGAnalyticsConfiguration.h
Link with an iOS app, set breakpoints in the appropriate UIApplication notification handlers.
Also set APPLICATION_EXTENSION_API_ONLY=YES to guard this at build time.
#213 
NA
**Questions:**
Yes, now by default the optional config.application will be nil unless a non-extension target sets it to UIApplication.shared.
No
- Do we need to update …
> Extract UIApplication to permit linkage with iOS extensions.

- Analytics/Analytics.h
Fixes 
when importing Segment via Carthage.
> Add missing includes to umbrella header

- Analytics/Classes/Internal/SEGHTTPClient.h
- Analytics/Classes/Internal/SEGHTTPClient.m
Solves issue https://github.com/segmentio/analytics-ios/issues/692#issuecomment-307870908
Reuse the session in client so we do not create it every time. 
When client deallocs, we invalidate the session.
> Reuse NSURLSession in SEGHTTPCLient

- Analytics/Classes/Internal/SEGHTTPClient.m
These two separate PRs unfortunately introduced conflicting changes
https://github.com/segmentio/analytics-ios/pull/699
https://github.com/segmentio/analytics-ios/pull/679
When we re-use session, we should no longer invalidate session right after each task.
> Fix NSURLSession being prematurely invalidated

- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/Utils/TestUtils.swift
This works around an Apple Swift mapping issue which was found by another developer after integrating the release with this PR: https://github.com/segmentio/analytics-ios/pull/698#issuecomment-315432202
See the change in AnalyticsTests.swift
No need to manually test, an automated test has been added to AnalyticsTests.swift which would have caught the issue.
Apple recommended the previous style of protocol extraction and conformance assignment at WWDC17. However, Swift mapping type mismatches will cause issues like this. Luckily it is fairly simple and straightforward to workaround them as needed.
Not aware …
> Add workaround for UIApplication type mismatch with Swift mapping.

- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGStoreKitTracker.m
- Analytics/Classes/SEGAnalytics.m
Property list serialization format (which we currently use for `SEGFileStorage`) does not support `NSNull` (e.g. `CFNull`) values. 
https://stackoverflow.com/questions/6244873/handling-cfnull-objects-in-nspropertylistserialization
As a result, when we send in `NSNull` values the queues will not be able to persist and error will be logged. https://github.com/segmentio/analytics-ios/blob/dev/Analytics/Classes/Internal/SEGFileStorage.m#L154
The longer term fix is to change our serialization format, the immediate hotfix is to stop sending `NSNull`'s in the core SDK and all integrations.
Tested manually confirming the issue has been fixed.
cc @ladanazita @f2prateek @TeresaNesteby @myclamm
> Hotfix: queue corruption from NSNull

- Analytics/Classes/Internal/SEGAnalyticsUtils.h
This PR changes the import of `"SEGSerializableValue.h"` to be a global import `<Analytics/SEGSerializableValue.h>` in `SEGAnalyticsUtils.h` file. Otherwise the file cannot be found when using Segment Analytics via Carthage in a project that uses Localytics integration.
1. Check out [this sample app](https://github.com/lbatr3s/SegmentLocalyticsSampleApp)
2. Run carthage bootstrap --platform iOS
3. Build the sample project.
As a result, you'll see a build failure with the error mentioned above.
Map the SegmentLocalyticsSampleApp's Cartfile to `lbatr3s/analytics-ios` branch `dev` instead, and verify the build is successfull. Note that your Cartfile should look as follows:
`github …
> Global import needed when using Segment Analytics via Carthage

- Analytics/Classes/Internal/SEGAnalyticsUtils.m
@ladanazita @TeresaNesteby 
Tested manually w/ @TeresaNesteby in test app and confirmed working.
> Use DEBUG preprocessor flag to conditionally disable assertions in prod

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- AnalyticsTests/AnalyticsTests.swift
Removes the ability for certain events to be delivered synchronously to integrations. 
It would be good to do a audit of integrations which need this functionality and make the fix I suggested for those integrations.
Closes #714.
> Always deliver events asynchronously to integrations.

- Analytics/Classes/Internal/SEGHTTPClient.h
- Analytics/Classes/Internal/SEGHTTPClient.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- AnalyticsTests/HTTPClientTest.swift
This refactors the internal implementation of the `sendData` to _create_
the HTTP requests on a new background queue. Note that this simply changes
the _creation_ of the request to the new background queue - the actual
execution was already on a background thread.
Previously, the creation would happen on the queueing thread. This
means that while the HTTP request was being _created_, events would not be
queued. By default, this is not a problem, the actual creation of the
request is a few milliseconds at most. However, this assumes that the request
factory customers might set only runs for a few milliseconds. A long running request
factory would have a chance of blocking the queueing thread for too long and
open a small window for data loss.
With this change, customers to add more complex …
> Create HTTP requests on a background queue.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
Ref:
https://paper.dropbox.com/doc/Sending-Disabled-Events-evdrvByT2cYUErnrbAUa3
> Send disabled events to Segment.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- AnalyticsTests/IntegrationsManagerTest.swift
If an event is not present in the tracking plan, we'll now lookup the schema defaults for the project.
If the event is disabled in the schema default, it will only be sent to the Segment integration (i.e. api.segment.io).
If the event is enabled in the schema default, it will be sent to all integrations.
Ref: https://paper.dropbox.com/doc/Schema-Client-Side-Defaults-DufdS8Ej43mnFXvvMqm1b
> Respect schema defaults.

- Analytics/Classes/Internal/UIViewController+SEGScreen.m
fixing issue number [729](https://github.com/segmentio/analytics-ios/issues/729)
app was crashing when `recordScreenViews ` is true and try to report a screen with no name (like UIAlertController) and the validation was failing because [top title] returns an empty string instead of nil, so, validation was only with nil, i add the empty validation to get the name of the class
> Fix validation when there’s no name of view controller

- Analytics/Classes/Integrations/SEGIntegration.h
This PR adds a missing import, which was causing a compiler warning, when using Segment Analytics via Carthage, in a project completely written in Swift.
1. Check out [this sample app](https://github.com/giorgiopaoloni/SegmentSampleApp)
2. Run `carthage bootstrap platform iOS`
3. Build the sample project
As a result, you'll get the compiler warning mentioned above.
Yes!. Map the Sample App's Cartfile to `giorgiopaoloni/analytics-ios` branch `dev` instead, and verify the warning is gone. Note that your Cartfile should look as follows:
```
github "giorgiopaoloni/analytics-ios" "dev"
```
Not really!
N/A …
> SEGIntegration: Importing Context

- Analytics/Classes/Internal/SEGHTTPClient.h
- Analytics/Classes/Internal/SEGHTTPClient.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- AnalyticsTests/HTTPClientTest.swift
This reverts commit 2e6c57d4146ae2f25b5b372a430224de10319c54.
For reference, there was a bug in this line (https://github.com/segmentio/analytics-ios/commit/2e6c57d4146ae2f25b5b372a430224de10319c54#diff-8ca45829c92fc1633fd8f6804bd3a0cbR87) where it was sending the `batch` directly rather than the `payload` object.
> Revert "Create HTTP requests on a background queue."

- Makefile
This is reqiured to properly build the Carthage binaries that are up to date with the source.
See #12.
> Makefile: archive should run carthage target.

- Analytics/Classes/SEGAnalytics.h
changes `+ (instancetype)sharedAnalytics;` to `+ (instancetype _Nullable)sharedAnalytics;`
at `+ (instancetype)sharedAnalytics;`
It shouldn't change any functionality so whatever sanity tests are normally run should suffice.
I discovered an instance where an event was attempting to be logged before the client was setup that failed silently. I think this would help prevent that from happening to others.
https://github.com/segmentio/analytics-ios/issues/743
**Questions:**
No
No
- Do we need to …
> sharedAnalytics returns null before setup

- Analytics/Classes/Internal/NSData+SEGGZIP.h
- Analytics/Classes/Internal/NSData+SEGGZIP.m
Renames GZIP category to prevent collisions
A naming collision happens when the Analytics library is used in a project that also imports the GZIP library as a pod.
#703
**Questions:**
- Does the docs need an update? **nope**
- Are there any security concerns? **nope**
- Do we need to update engineering / success? **nope**
> Renames GZIP category to prevent collisions

- Analytics/Classes/Internal/SEGSegmentIntegration.m
We only set this key on tvOS, so let's remove it only on tvOS as well.
Ref LIB-130, closes #671.
> Reset SEGUserIdKey only on tvOS

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGAnalyticsUtils.h
- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- AnalyticsTests/AnalyticsUtilTests.swift
Previously we didn't cap the queue, and when we added the limit, we only removed the oldest element, rather than fully shrink the queue.
Hence there are cases where the queue may already be larger than 1000 events, and removing a single element at a time isn't as helpful. Now we delete as many events as required to trim the queue size.
Ref: LIB-210
> Ensure queue is always < 1000 items.

- Analytics/Classes/Internal/SEGHTTPClient.m
- AnalyticsTests/HTTPClientTest.swift
As per the library guidelines (https://paper.dropbox.com/doc/Analytics-library-guidelines-2trBhLKQD4Soz4VatvuGR#:uid=189560039280582553736180&h2=Handling-Network-Errors), we should be retrying requests when the server responds with HTTP 429 status.
> Retry HTTP 429 status codes.

- AnalyticsTests/EndToEndTests.swift
- Makefile
- circle.yml
Runscope shutdown the traffic inspector (https://blog.runscope.com/posts/phasing-out-traffic-inspector) we were using for our tests.
This migrates to the custom webhook replacement we had built.
Also removes unused xctool commands/updates their usage.
Ref: LIB-458
> use schema webhook

- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/Utils/TestUtils.swift
> Add a `flushInterval` configuration option

- Analytics/Classes/Internal/SEGAnalyticsUtils.h
- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/Utils/TestUtils.swift
> Add a `maxQueueSize` configuration option

- Makefile
- circle.yml
This is to standardize the makefile as per https://paper.dropbox.com/doc/Analytics-library-guidelines--ALQnS2w9_tQGT30FmYaTEhfEAg-2trBhLKQD4Soz4VatvuGR#:uid=966747111832373010643230&h2=Standardized-Makefile
> rename install target to dependencies

- Analytics.xcodeproj/project.pbxproj
- Makefile
- Podfile.lock
Ref: LIB-546
This should help speed up `pod install` and make it possible to update the lock on latest versions.
See [Cocoapods changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#153-2018-05-25).
> Upgrade to Cocoapods 1.5.3

- .circleci/config.yml
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/EndToEndTests.swift
This PR fixes 3 common source of failure for our test :
1. ~Deadlock : sometimes the test runner freeze and needs a total clean to be run. We fix this by removing the need to call the main thread in SegmentIntegration~ Moved to #784
2. Missing iOS simulator : Adding a command to list the simulators seems to magically fix the issue.
3. Flaky maxQueueSize test : I rewrote this one to be more stable
We ran 21+ successful and consecutive test iterations : https://circleci.com/gh/segmentio/workflows/analytics-ios/tree/fix%2Fflaky-test
Ref : LIB-543
> Fix flaky tests

- Analytics/Info.plist
- RELEASING.md
This allows for the framework to be used in Swift 4 projects who consume this framework from Carthage, to be submitted to the App Store.
Closes #794
By reading #794
Create a project with Swift 4, consume this framework with Carthage, and then submit it to the App Store 😅
#794
#794
> Remove -beta suffix from CFBundleShortVersionString

- Analytics/Classes/Internal/SEGUtils.h
- Analytics/Classes/Internal/SEGUtils.m
- Analytics/Classes/SEGAnalytics.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests-Bridging-Header.h
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/AnalyticsUtilTests.swift
- AnalyticsTests/Utils/TestUtils.swift
- Podfile
- Podfile.lock
> Add deep links redaction

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/SEGAnalytics.m
- AnalyticsTests/TrackingTests.swift
- Examples/CocoapodsExample/CocoapodsExample/AppDelegate.m
Historically, the iOS library has allowed setting a custom anonymous identifier (https://github.com/segmentio/analytics-ios/pull/485).
During adding middlewares, a bug was introduced which started ignoring the anonymousId option.
This fixes the bug and adds a test to validate the fix. This was also tested in the example app end to end and I've verified that events show up with the custom anonymousId.
Historically, the iOS library has allowed setting a custom anonymous identifier (https://github.com/segmentio/analytics-ios/pull/485).
During adding middlewares, a bug was introduced which started ignoring the anonymousId option.
This fixes the bug and adds a test to validate the fix. This was also tested in the example app end to end and I've verified that events …
> fix: allow setting anonymousId

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
Modifies one line of code to remove a warning from Xcode.
From the top. There's only one line that changed (added 8 characters).
This change is purely syntactical and functionality will not be impacted.
**Questions:**
- Does the docs need an update? - NO -
- Are there any security concerns? - NO -
- Do we need to update engineering / success? - NO -
> 1-line change that fixes a warning in Xcode

- Analytics/Classes/Internal/SEGSegmentIntegration.m
Fixes issue 38 in React Native SDK https://github.com/segmentio/analytics-react-native/issues/38
According to Kochava destination docs (https://segment.com/docs/destinations/kochava/#getting-started),  `context.device.type` (has value of ‘ios’ or ‘android’), `context.device.advertising_id` (IDFA on iOS and adID on Android) and `context.device.id` are required in all calls to Kochava. 
`context.device.type` was not being collected, and this fixes data not being shown in Kochava.
> Add missing context.device.type field required for Kochava integration.

- .clang-format
Removes the broken `.clang-format` symlink.
Nope, but you might need to commit a real `.clang-format` file.
It was a symlink to a file on one of the dev's local machines, so there's really no reason at all to have it here. If you insist on having a `.clang-format` file in the repo we ought to commit a real one.
No tickets.
**Questions:**
- Does the docs need an update? -- No
- Are there any security concerns? -- No
- Do we need to update engineering / success? -- No
> Remove broken .clang-format symlink

- Analytics.xcodeproj/project.pbxproj
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Podfile
- Podfile.lock
Add's collection of "name" field to the iOS library, and updates Nimble to version 7.3.4
N/A
N/A
Done to match collection of data in Android library. Android was collecting both the model and name of the device, whereas iOS was only collecting the model. Libraries will now have parity and match the Segment Spec.
https://segment.atlassian.net/browse/LIB-837
N/A
**Questions:**
No, this is how functionality was outlined in the Spec to begin with.
N/A …
> adding “name” field to payload;updated nimble to version 7.3.4

- Analytics/Classes/Internal/SEGSegmentIntegration.m
I'm putting this in WIP until we're confident this will not result in regressions.
---
Sometimes the test runner freeze and needs a total clean to be run. We fix this by removing the need to call the main thread in SegmentIntegration by using the proper `NSRunLoop` API.
[Prateek noted](https://github.com/segmentio/analytics-ios/pull/784#discussion_r219051393) :
> We've had some issues around concurrency - particularly as the threads we initialize integrations is not guaranteed.
>
> This causes some integrations and customers to rely on implementation details
that have caused a few issues in the past (#518, #714, #683) so I'd like to be a bit careful rolling this out.
> Fix GCD mutual dependency

- .circleci/config.yml
- Analytics/Classes/SEGAnalytics.m
- AnalyticsTests/AnalyticsTests.swift
- Podfile
Adds the iOS Backgrounded event to the tracking for lifecycle events when enabled
Link against the library and send the app to background. You should see the backgrounded event.
Link against the library and send the app to background. You should see the backgrounded event.
This is part of the work from Formidable 
LIB-1143
**Questions:**
- Does the docs need an update? No (The docs already mention the event)
- Are there any security concerns? No
- Do we need to update engineering / success? No
> Add iOS Backgrounded Event.

- Analytics.podspec
- Analytics/Classes/SEGAnalytics.m
- CHANGELOG.md
- Examples/CarthageExample/Cartfile
- README.md
* Prepare for release 3.7.0
* Updated cartfile.
* Updated version in SEGAnalytics.m
* Updated version in readme instructions.
> Promoting 3.7.0-beta.4 to release. (#834)

- Analytics.podspec
This makes sure that `CoreTelephony` is only included for iOS targets.
Build a tvOS target with Cocoapods. Include `pod 'Analytics'` as a dependency. Building for actual tvOS hardware (not simulator) will fail. Using this changed podspec will remove the dependency for `CoreTelephony` in tvOS, and will fix the linker error.
https://github.com/segmentio/analytics-ios/issues/841
**Questions:**
No
- Are there any security concerns? 
No
No
> `CoreTelephony` library is now only included on iOS targets. 

- Analytics.xcodeproj/project.pbxproj
- Analytics.xcodeproj/xcshareddata/xcschemes/Analytics.xcscheme
- Analytics.xcodeproj/xcshareddata/xcschemes/AnalyticsTests.xcscheme
- Analytics/Classes/Internal/SEGAnalyticsUtils.h
- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGFileStorage.m
- AnalyticsTests/SerializationTests.m
- Stops blindly passing dictionaries.
- Property dictionaries are checked for NSCoding conformance to ensure they can be serialized.
- Non NSCoding conformant properties trigger an assert in DEBUG builds.
- Property dictionaries are deep copied so contents can’t change while the pipeline is in progress.
- Puts a try/catch arrangement as a temporary guard against crashes for serialization failures until the storage format can be changed.
> Fix for LIB-1416 & Github #846

- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGFileStorage.m
- AnalyticsTests/MiddlewareTests.swift
- AnalyticsTests/TrackingTests.swift
- Podfile.lock
- Changes the storage format for SEGFileStorage to use JSON instead of plists.
- Perform conversion on existing plist format files as encountered.
LIB-1494 and #852
**Questions:**
NO
NO
NO
> Swapped JSON in for the storage format instead of plists.

- Analytics/Classes/Integrations/SEGIntegrationsManager.h
- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- AnalyticsTests/IntegrationsManagerTest.swift
- Fixes issue where customers overwrite information regarding integration enablement.
- If the server-supplied key doesn't contain the right type (a bool), an assertion is thrown.
- Adds tests to validate this as well as existing fallback functionality.
LIB-1462
**Questions:**
NO
NO
NO
> Fixed LIB-1462

- Analytics.xcodeproj/project.pbxproj
- Analytics/Classes/Internal/SEGMacros.h
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/Internal/SEGUtils.m
- Break out the set/get of the cachedStaticContext
- Respond to ApplicationWillEnterForeground so we can update said context.
- Put locking around static context access.
- Removed extraneous NSNull checks that were causing tests to fail.
LIB-1522
**Questions:**
NO
NO
NO
> Reload static context data when the app returns from background.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- AnalyticsTests/IntegrationsManagerTest.swift
- Correctly supports previously documented behavior.
- A dictionary being supplied into integrations defaults enablement to TRUE.
- Bool still functions as expected.
> Address Issue #851; Expect dictionary as well for for integration enablement

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Uses previously cached settings if unable to retrieve from server.
- Settings were being cached already, just not used.
- If no settings are present (server or cached), fallback to the barebones config.
> LIB-1634: Fallback to last settings loaded on iOS

- Analytics/Classes/Internal/SEGHTTPClient.h
- Analytics/Classes/Internal/SEGHTTPClient.m
- AnalyticsTests/HTTPClientTest.swift
PR implements a check when payload excesses size of 500KB.
The issue from https://github.com/segmentio/analytics-ios/issues/871
**Questions:**
> Implement maximum batch request size

- Analytics.xcodeproj/project.pbxproj
- Analytics.xcodeproj/xcshareddata/xcschemes/Analytics.xcscheme
- Analytics.xcodeproj/xcshareddata/xcschemes/AnalyticsTests.xcscheme
- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/Internal/SEGUtils.h
- Analytics/Classes/Internal/SEGUtils.m
- Analytics/Classes/Middlewares/SEGContext.h
- Analytics/Classes/Middlewares/SEGContext.m
- Analytics/Classes/Middlewares/SEGMiddleware.h
- Analytics/Classes/Middlewares/SEGMiddleware.m
- Analytics/Classes/SEGAnalytics.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Analytics/Classes/SEGAnalyticsConfiguration.m
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/MiddlewareTests.swift
- AnalyticsTests/StoreKitTrackerTests.swift
- AnalyticsTests/TrackingTests.swift
- AnalyticsTests/Utils/TestUtils.swift
- Adds integration middleware capabilities.
- Adds tests for integration middleware.
- Deprecates existing `middleware` property on SEGConfiguration and points users to `sourceMiddleware` instead.  
- `middleware` property has been re-routed to sourceMiddleware if used.
- Modifies tests to use sourceMiddleware.
- Tests cover this functionality, N/A
LIB-1567
**Questions:**
YES
NO
YES
> Added Integration Middleware capabilities

- .gitignore
- Analytics/Classes/Internal/SEGFileStorage.m
Fixed a crash in the file storage when trying to get a string stored using old SDK version.
`SEGFileStorage.m`
You need a version of SDK where the string is converted to Data directly without encapsulating it into the Dictionary object. After that upgrade to the version from the PR and it shouldn't crash.
To avoid such crashes in the future some migration logic would be helpful.
No tickets I know about.
No UI/UX changes.
**Questions:**
No.
No.
No.
> Fixed a crash in the file storage

- Analytics/Classes/Integrations/SEGIntegrationsManager.h
- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGSegmentIntegration.h
Makes filenames used for data storage public.
It's very short.
I don't think there's anything to test.
Yes, so I need those filenames to be public since my application often starts before a device is unlocked. In such cases Segment library is booted but it fails to read its files/data and then reports analytic events without a `user_id`. Moreover, during such "corrupted" sessions it's using a new `anonymous_id`.
A followup-fix on my application side will be to change `FileProtectionType` of the library files to `.none`. I'm not sure if that's something you'd like to do for all your users, so this PR only publishes those file names.
**What …
> Publish filenames used for data storage

- Analytics.xcodeproj/project.pbxproj
- Analytics.xcodeproj/xcshareddata/xcschemes/AnalyticsTests.xcscheme
- Analytics/Analytics.h
- Analytics/Classes/Internal/SEGScreenReporting.h
- Analytics/Classes/Internal/UIViewController+SEGScreen.h
- Analytics/Classes/Internal/UIViewController+SEGScreen.m
- AnalyticsTests/AnalyticsTests-Bridging-Header.h
- AnalyticsTests/AutoScreenReportingTest.swift
- AnalyticsTests/UIViewController+SegScreenTest.h
- AnalyticsTests/Utils/TestUtils.swift
- Podfile.lock
Adds the ability to specify a custom name and custom properties during
automatic screen reporting. 
Also fixes `seg_topViewController()` for `UITabBarController` and custom
container view controllers.
`UIViewController.seg_viewDidAppear()`
* Create a UIViewController, and conform to the new `SEGScreenReporting`
protocol.  
* Implement `seg_trackScreen` to override the default screen tracking.  Your implementation should call `seg_screen` with custom values for the `screen`, `properties` and/or `options` arguments.
* Implement `seg_mainViewController` to specify which child view
controller of a custom container view controller should be referenced
when determining the top view controller …
> Custom name/properties for auto screen reporting

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGAnalyticsUtils.h
- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- Adds ability to set `default` settings if segment.com can't be reached.
> Add ability to set default settings is segment.com can't be reached.

- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/Internal/SEGSegmentIntegration.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- AnalyticsTests/AnalyticsTests.swift
- IDFA is moved completely external.
- Customers must now set a adSupportBlock which will get called (so they can retrieve IDFA, not us).
- References to AdSupport framework have been removed.
> Makes IDFA support externally/customer driven.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Middlewares/SEGMiddleware.h
- Analytics/Classes/Middlewares/SEGMiddleware.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
- AnalyticsTests/MiddlewareTests.swift
- Examples/CarthageExample/Cartfile.resolved
- Renames middleware methods to match a.js naming.
- Updates tests to use the new names.
> Renamed middleware methods to match a.js naming.

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/Internal/SEGAnalyticsUtils.h
- Analytics/Classes/Internal/SEGAnalyticsUtils.m
- Analytics/Classes/SEGAnalyticsConfiguration.h
This PR brings the defaultSettings configuration option and usage logic from the 4.x series back to the 3.x series.  This is necessary to support react native until all device mode integrations have been updated such that they are no longer version pinned to 3.x.
> Backport defaultSettings feature from 4.x to 3.x.

- Analytics/Classes/Internal/UIViewController+SEGScreen.m
This simply reverses the logic for naming conventions regarding automatic screen tracking in an attempt to provide more consistent naming conventions. The current approach is sacrificing consistency for readability which muddies up data. With the addition of the custom naming protocol, we don't need `title` anymore.
Assuming that all view controllers have a somewhat unique name (other than ViewController which is specified in the logic), we can assume that the automatic screen tracking will have a consistent naming convention throughout all screens (rather than having a mix of both `ClassName` minus "ViewController" and `title`), since all view controllers will not have a `title` i.e `NavigationItem`.
Furthermore, if two view controllers have the same `title`, …
> Automatic Screen Tracking with consistent naming conventions

- Analytics/Classes/Integrations/SEGIntegrationsManager.m
- Analytics/Classes/SEGAnalytics.m
Brings back the notification condition for lifecycle events. This limits the amount of notifications sent out to only limit specifically to Segment analytics.
> Added application object back to notifications

- Analytics.xcodeproj/project.pbxproj
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/AnalyticsUtilTests.swift
- AnalyticsTests/AutoScreenReportingTest.swift
- AnalyticsTests/ContextTest.swift
- AnalyticsTests/CryptoTest.swift
- AnalyticsTests/FileStorageTest.swift
- AnalyticsTests/HTTPClientTest.swift
- AnalyticsTests/IntegrationsManagerTest.swift
- AnalyticsTests/MiddlewareTests.swift
- AnalyticsTests/StoreKitTrackerTests.swift
- AnalyticsTests/TrackingTests.swift
- AnalyticsTests/UserDefaultsStorageTest.swift
- AnalyticsTests/Utils/TestUtils.swift
- Podfile
- Podfile.lock
Removes Quick and Nimble and updates the tests back to standard Apple conventions.
Start by running tests. Then make sure the tests that happen over an unknown amount of time work.
Running tests and random individual tests.
Xcode didn't allow running individual tests, made it difficult to upgrade if the libraries became outdated. 
LIBMOBILE-77
**Questions:**
> LIBMOBILE-77: Removed Quick and Nimble, updated unit tests

- Analytics.xcodeproj/project.pbxproj
- AnalyticsTests/AnalyticsTests.swift
- AnalyticsTests/AnalyticsUtilTests.swift
- AnalyticsTests/AutoScreenReportingTest.swift
- AnalyticsTests/ContextTest.swift
- AnalyticsTests/CryptoTest.swift
- AnalyticsTests/FileStorageTest.swift
- AnalyticsTests/HTTPClientTest.swift
- AnalyticsTests/IntegrationsManagerTest.swift
- AnalyticsTests/MiddlewareTests.swift
- AnalyticsTests/StoreKitTrackerTests.swift
- AnalyticsTests/TrackingTests.swift
- AnalyticsTests/UserDefaultsStorageTest.swift
- AnalyticsTests/Utils/TestUtils.swift
- Package.swift
- Podfile
- Podfile.lock
Fixes Issue 906
Use a test project to verify all types work
https://github.com/segmentio/analytics-ios/issues/906
https://github.com/segmentio/analytics-ios/issues/908
**Questions:**
> Spm update

- Package.swift
The latest 4.0.2 works on macOS via Catalyst, building through Swift Package Manager, assuming you add CoreTelephony to the list of linked frameworks.
However, if you attempt to view a SwiftUI preview on an app linking Analytics, you'll get the following issue:
```
Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
objc-class-ref in Analytics.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
when trying to view the preview. As far as I can tell, SwiftUI previews turn SwiftPM static libraries into dynamic libraries, so they need to fully resolve their linkage at *library* build time, instead of app build time.
Adding CoreTelephony to the linker settings fixes …
> Fix SwiftUI previews in macOS Catalyst builds

- Analytics/Internal/SEGFileStorage.m
- AnalyticsTests/FileStorageTest.swift
- Fixes #924 
- Since clients of v3.8.0+ will need to update to remove invalid JSON values in order to send new events, the changes here "match" the behavior by disregarding any events that can't be converted to valid JSON. Not ideal, but works without requiring support for both plists and json and is consistent in that events emitted from v3.8.0+ will only have values that work in JSONSerialization.
n/a, pretty small diff here
1. Attempt to track events with `TimeInterval.nan` as values while offline on v3.7.0
2. Upgrade to a version with these changes and avoid a crash
(added some unit tests to approximate this)
See #924 for more info
> Disregard payloads that fail conversion from plist to json backing

- Analytics/Internal/SEGUtils.m
Fixes an issue where device was in the payload twice.
Look at version 4.0.4 vs this PR. 4.0.4 contained the issue, 4.0.3 did not. Compare SEGUtil
Run to see the payload, verify device isn't doubled up.
LIBMOBILE-149
**Questions:**
> [LIBMOBILE-149] Fixed double device payload

- Segment.xcodeproj/project.pbxproj
- Segment/Classes/SEGWebhookIntegration.h
- Segment/Classes/SEGWebhookIntegration.m
- Segment/Classes/Segment.h
- Segment/Internal/SEGIntegrationsManager.m
- SegmentTests/AnalyticsTests.swift
This change adds a webhook device-mode destination. This is being added solely for debugging/observability purposes but can used for other use cases as well.
SEGWebhookIntegration.m
use the new WebhookIntegrationFactory integration with a valid webhook url (can retrieve one from [webhook.site](https://webhook.site/)), and proceed to send events. The webhook should receive events if correctly configured.
Code:
```swift
let configuration = AnalyticsConfiguration(writeKey: WRITE_KEY)
let webhookDestination : SEGIntegrationFactory = WebhookIntegrationFactory.init(name: "dest1", webhookUrl: "<webhookURL>")
configuration.use(webhookDestination)
``` …
> Add WebhookIntegration

- Segment/Classes/SEGAnalytics.m
- Segment/Classes/SEGAnalyticsConfiguration.m
- Removes configuration shimmy from SEGAnalytics and puts it in SEGAnalyticsConfiguration where it belongs.
- Stops trying to double wrap options in array.
> Fix configuration setting for edgefn

- Segment/Classes/SEGAnalytics.h
- Segment/Classes/SEGAnalytics.m
- Segment/Classes/SEGScreenPayload.h
- Segment/Classes/SEGScreenPayload.m
- SegmentTests/TrackingTests.swift
Adds 3 new versions of the screen call to allow category to be passed while maintaining compatibility with previous call points.
```
- (void)screen:(NSString *)screenTitle category:(NSString * _Nullable)category properties:(SERIALIZABLE_DICT _Nullable)properties options:(SERIALIZABLE_DICT _Nullable)options;
- (void)screen:(NSString *)screenTitle properties:(SERIALIZABLE_DICT _Nullable)properties options:(SERIALIZABLE_DICT _Nullable)options;
- (void)screen:(NSString *)screenTitle category:(NSString * _Nullable)category properties:(SERIALIZABLE_DICT _Nullable)properties;
- (void)screen:(NSString *)screenTitle properties:(SERIALIZABLE_DICT _Nullable)properties;
- (void)screen:(NSString *)screenTitle category:(NSString * _Nullable)category;
- (void)screen:(NSString *)screenTitle;
```
> Added category option to screen calls

- Segment/Internal/SEGUtils.m
- SegmentTests/SerializationTests.m
- Fixes issue with NSCopying conformance being checked before SEGSerialization causing non-serializable items to make it through.
- Addresses #959, #947, and PR #954
> Fixed issue w/ NSCopying being used before SEGSerialization

- Analytics.podspec
- README.md
Added the capability for the pod to be built as a static framework
Test with Swift and Objective-C. It may be appropriate to use `use_modular_headers!` or `use_frameworks! :linkage => :static` in the Podfile
See above
Github issue: https://github.com/segmentio/analytics-ios/issues/752
https://segment.atlassian.net/browse/LIBMOBILE-211
**Questions:**
> Added static lib support for cocoapods

- Segment/Classes/SEGAnalytics.m
- Fixes issue where IDFA is not updated until after a user has left the app and returned.
- Check IDFA values if ad-tracking enabled to determine if context needs to be rebuilt.
> Pull IDFA if it has changed and rebuild context if necessary.

- Segment/Internal/SEGIntegrationsManager.m
Fix a build failure with the newly released Xcode 12.5 beta 1
Try to build the Swift Package with Xcode 12.5 beta 1
Build.
Xcode 12.5 beta 1 was released today, and introduces a new error when a `#if` statement is used with an undefined variable: "error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0". This affects a single file, `SEGIntegrationsManager.m`.
**Questions:**
No.
No.
No.
> Fix the build of the Swift Package with Xcode 12.5 beta 1

- Segment/Classes/SEGReachability.m
Code copied for this specific function (currently unused) from https://github.com/tonymillion/Reachability/blob/ea5dd8d4646ecb2f0d07e6619827df1dfea809b8/Reachability.m#L501
Fixes warning in Xcode 12.5 Beta 2 (12E5234g).
Change is backward compatible with Xcode 12.4 and likely earlier Xcode versions.
Build existing codebase in Xcode 12.5 Beta 2 to observe warning.
The description function is not actually used, and is only included by virtue of being copied from the Reachability project. In any case, I manually tested by calling `description` after the SEGReachability instance was initialized like so:
`self.reachability = [SEGReachability reachabilityWithHostname:@"google.com"];` …
> Fix new warning in Xcode 12.5 Beta 2 (12E5234g): "Cast to smaller integer type 'unsigned int' from 'SEGReachability *'".

- Segment/Classes/SEGAnalytics.m
- Segment/Internal/SEGIntegrationsManager.h
- Segment/Internal/SEGIntegrationsManager.m
- SegmentTests/AnalyticsTests.swift
- Makes anonId save happen up in the identify() call now rather than in the guts of the system.
- Makes it such that middleware can modify the anonId without changing it for the entire system.
- Fixes #974
> Pushed save of anonId higher up into the flow.

- Segment/Classes/SEGSegmentIntegration.h
- Segment/Classes/SEGSegmentIntegration.m
- Segment/Classes/SEGSegmentIntegrationFactory.m
- Segment/Internal/SEGIntegrationsManager.m
- Standardizes name for the segment destination into a const across the project.
- Makes building default settings object less complex.
> Fixed issue where incorrect segment settings could be built

- Segment/Classes/Segment.h
Fixes #988 by adding missing import
Check that I've imported the correct file
Try to add Segment to a project and compile using Xcode 12.5. It won't compile and will tell you that an import is missing.
Nope
#988 
None
**Questions:**
No
Not afaik
No idea what this is 😅
> Add missing import in Segment.h

- Analytics.podspec
- Segment.xcodeproj/project.pbxproj
- Reverts analytics-ios 4.1.3 change to build statically.
- Resolves #991
> Revert static lib podspec change.

- Segment/Internal/SEGIntegrationsManager.h
Added missing nullability identifier to deal with this issue
https://github.com/segmentio/analytics-ios/issues/997
> Added missing nullability identifier

- Segment/Internal/SEGIntegrationsManager.m
Fixes #1008
`Segment/Internal/SEGIntegrationsManager.m`
it is small change
Requirements:
- App integrating segment SDK
- Fresh install of an app
- Amplitude integration configured
- Luck
This is race condition so it happens infrequently. To emulate problematic condition failing always before and not failing after the fix add `[NSThread sleepForTimeInterval:3];` inside `-[SEGIntegrationsManager setCachedSettings:]` line before `[self updateIntegrationsWithSettings:settings[@"integrations"]];`
See #1008
#1008
not UI/UX change
**Questions:**
- Does the docs …
> Fix deadlock on first app launch

- Package.swift
Removed unused exclude in Package.swift which generates a warning in Xcode 13.
Closes #1015
> Removed unused exclude in Package.swift

- Segment.xcodeproj/project.pbxproj
- Segment/Internal/SEGUserDefaultsStorage.m
- Segment/Internal/SEGUtils.h
- Segment/Internal/SEGUtils.m
- SegmentTests/AnalyticsTests.swift
- SegmentTests/Utils/tvOSSettingsBad.json
- Fixed issue where a `null` value in the /settings endpoint response would crash tvOS.
- Added a test case to verify fix.
> Fix null settings entry crash on tvOS

- Segment/PrivacyInfo.xcprivacy
adds a privacy manifest for iOS 17
at the privacy manifest 
not really necessary 
we need it for iOS 17
n/a 
**Questions:**
no
no
yes but docs are already in motion
> feat: add privacy manifest for ios 17
